<?php
class User{
    public $id;
    public $name;
    public $tel;
    public $login;
    public $password;

    public function __construct($id,$name,$tel,$login,$password)
    {
        $this->id = $id;
        $this->name = $name;
        $this->tel = $tel;
        $this->login = $login;
        $password = $this->hashPassword();
        $this->password = $password;
    }
    public function getUserData(){
        echo "Hello $this->name.<br>Your login is: $this->login<br>You telephone: $this->tel<br>$this->password <hr>";
    }
    protected function hashPassword(){
         $password = md5($this->password);
         return $password;
    }
}

class UserAdmin extends User{
    public $role;
    public function __construct($id, $name, $tel, $login, $password, $role)
    {
        parent::__construct($id, $name, $tel, $login, $password);
        $this->role = $role;
    }
   public function getUserData()
{
    parent::getUserData(); // TODO: Change the autogenerated stub
    echo "Your role {$this->getRole()}";
}
    public function getRole(){
    return $this->role;
}
}

$user1 = new User(1,'Anna', '+79110285853','anutka0306','12345');
$user1->getUserData();

$user2 = new UserAdmin(2,'Admin', '+79110285853','admin','12345','Admin');
$user2->getUserData();